//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWingsAir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aviones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aviones()
        {
            this.Vuelos = new HashSet<Vuelos>();
        }
    
        public int IdAvion { get; set; }
        public string Codigo { get; set; }
        public int IdTipoAvion { get; set; }
        public int HorasVuelo { get; set; }
        public int Capacidad { get; set; }
        public bool Estatus { get; set; }
    
        public virtual TipoAvion TipoAvion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vuelos> Vuelos { get; set; }
    }
}
