//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWingsAir.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WingsAirEntities : DbContext
    {
        public WingsAirEntities()
            : base("name=WingsAirEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aeropuertos> Aeropuertos { get; set; }
        public virtual DbSet<Aviones> Aviones { get; set; }
        public virtual DbSet<Pilotos> Pilotos { get; set; }
        public virtual DbSet<TipoAvion> TipoAvion { get; set; }
        public virtual DbSet<TipoPiloto> TipoPiloto { get; set; }
        public virtual DbSet<Vuelos> Vuelos { get; set; }
    }
}
