//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWingsAir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pilotos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pilotos()
        {
            this.Vuelos = new HashSet<Vuelos>();
        }
    
        public int IdPiloto { get; set; }
        public string NombreCompleto { get; set; }
        public bool Sexo { get; set; }
        public int HorasVuelo { get; set; }
        public bool Estatus { get; set; }
        public int IdTipoPiloto { get; set; }
    
        public virtual TipoPiloto TipoPiloto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vuelos> Vuelos { get; set; }
    }
}
