//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWingsAir.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelos
    {
        public int IdVuelo { get; set; }
        public string Numerovuelo { get; set; }
        public string Estatus { get; set; }
        public int IdPiloto { get; set; }
        public int IdAvion { get; set; }
        public int IdOrigen { get; set; }
        public int IdDestino { get; set; }
        public System.DateTime FechaVuelo { get; set; }
    
        public virtual Aeropuertos Aeropuertos { get; set; }
        public virtual Aeropuertos Aeropuertos1 { get; set; }
        public virtual Aviones Aviones { get; set; }
        public virtual OrigenDestino OrigenDestino { get; set; }
        public virtual OrigenDestino OrigenDestino1 { get; set; }
        public virtual Pilotos Pilotos { get; set; }
    }
}
